steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/trading-dashboard:$COMMIT_SHA
      - .

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/trading-dashboard:$COMMIT_SHA

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - trading-dashboard
      - --image
      - europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/trading-dashboard:$COMMIT_SHA
      - --region
      - europe-west1
      - --allow-unauthenticated
      - --min-instances
      - '1'
      - --memory
      - '512Mi'

images:
  - europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/trading-dashboard:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
